config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to: 'homes#top' 
 get "/home/about" => "homes#about", as: "home/about_path"
 
 resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
 resources :users, only: [:create, :index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :user

 
 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy
 attachment :profile_image
 
 validates :name, length: { minimum: 2 }
 validates :name, length: { maximum: 20 }
 validates :introduction, length: { maximum: 50 }
 validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sigh_out_path_for
    home_about_path_url
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user ==  current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    else
      if @book.update(book_params)
        flash[:notice] = "You have updated book successfully."
        redirect_to book_path(@book.id)
      else
        render :edit
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user.id = current_user.id
    @book.save
    redirect_to book_path(@book.id)
  end

  def show
   @user = User.find(params[:id])
   @new_book = Book.new
   @books = @user.books
  end

  def edit
   @user = User.find(params[:id])
   if @user != current_user
    redirect_to user_path(current_user.id)
   end 
  end



  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
   else
    render :edit
   end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
 <h2>User info</h2>
   <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
     <tbody>
      <tr>
       <th>name</th>
       <th><%= user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
      </tr>
     </body>
    </table>
    <div class="row">
　    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container mt-3">
 <% if @book.errors.any? %>
  <div class="errors text-danger">
   <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
   <li>
    <% @book.errors.full_messages.each do |message| %>
     <%= message %>
    <% end %>
   </li>
  </div>
 <% end %>
 <div class="row">
  <div class="col-md-5 mx-auto">
   <h2>Editing Book</h2>
   <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
     <label for="Book-title">Title</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div classs="form-group">
     <label for="Book-Opinion">Opinion</label>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="button mt-2">
     <%= f.submit "Update Book", class: "btn btn-success" %>
    </div>
   <% end %>

   <span>
    <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
   </span>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container mt-3 px-5">
<% if @book.errors.any? %>
 <div class="errors text-danger">
  <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  <li>
   <% @book.errors.full_messages.each do |message| %>
    <%= message %>
   <% end %>
  </li>
 </div>
<% end %>
 <div class="row">
  <div class="col-md-3">
  <%= render 'books/list', user: @user %>

   <div class="mt-3">
    <h2>New book</h2>
   </div>
   <%= form_with model: @book, local:true do |f| %>
    <div class="form-group">
     <label for="Book-Title">Title</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="Book-Opinion">Opinion</label>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="button">
     <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
    <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class="table table-hover">
    <thead>
     <tr>
      <th></th>
      <th>
       <strong>Title</strong>
      </th>
      <th>
       <storng>Opinion</storng>
      </th>
     </tr>
    </thead>
    <tbody>
     <% @books.each do |book| %>
     <tr>
      <td>
       <%= link_to user_path(book.user.id) do %>
        <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
       <% end %>
      </td>
      <td>
       <%= link_to book_path(book.id) do %>
        <%= book.title %>
       <% end %>
      </td>
      <td><%= book.body %></td>
     </tr>

     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>



<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
　
  
    </div>
    <div class='col-md-8 offset-md-1'>
      
      

    </div>
  </div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <%= render 'books/list', user: @user %>
     <div class="mt-3">
        <h2>New book</h2>
      </div>
      <%= form_with model: @new_book, local:true do |f| %>
        <div class="form-group">
            <label for="Book-Title">Title</label>
            <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="Book-Opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="button">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
　    <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
               <%= attachment_image_tag @book.user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
              <% end %><br/>
              <%= link_to @book.user.name, user_path(@user.id) %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td>
                <div clas="button">
                  <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success text-light" %>
                </div>
              </td>
              <td>
                <%= link_to book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                  <button type="button" class="btn btn-sm btn-danger text-white">Destroy</button>
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>



<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
　
  
    </div>
    <div class='col-md-8 offset-md-1'>
      
      

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container mt-5">
 <div class="row">
  <dev class="mx-auto">
   <h1>
    welcome to
    <i class="fas fa-book"></i>
    <storng>Bookers !!</storng>
   </h1>
  </div>
 </div>
</div> 

app/views/homes/top.html.erb
<div class="container mt-5">
 <div class="row">
  <dev class="mx-auto">
   <h1>
    welcome to
    <i class="fas fa-book"></i>
    <storng>Bookers !!</storng>
   </h1>
   <p>In<i class="fas fa-book"></i>
    <strong>Bookers</strong>
   </p>
   <p>
   you can share and exchange your opinions , inpressions , and emotions<br/>
   about various books !!
   </p>

   <dev class="row">
    <dev class="col-11 mb-3">
     <div class="btn btn-info btn-sm btn-block">
      <%= link_to "Log in", new_user_session_path, class: "text-light nav-link" %>
     </div>
    </dev>
   </dev>

   <div class="row">
    <div class="col-11">
     <div class="btn btn-success btn-sm btn-block">
      <%= link_to "Sign Up", new_user_registration_path, class: "text-light nav-link" %>
     </div>
    </div>
   </div>

  </div>

 </dev>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
      <div class="navbar-brand text-white">
       <%= link_to "Bookers", root_path, class: "text-light nav-link" %>
      </div>

      <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
      　 <li><%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %></li>
        <li><%=link_to "Users", users_path, class: "fas fa-users nav-link text-light" %></li>
        <li><%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %></li>
        <li><%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
       <% else %>
         <li><%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %></li>
         <li><%= link_to "About", home_about_path_path, class: "fas fa-link nav-link text-light" %></li>
      　  <li><%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
         <li><%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
       <% end %>
     　 </ul>
     </div>
    </nav>
   </header>
    <% if flash[:notice] %>
     <div class="flash text-success">
     <%= flash[:notice] %>
     </div>
     <% end %>
    <%= yield %>

    <footer>
     <div class="container mt-5">
      <div class="row">
       <div class="mx-auto">
        <p>CopyRight Infratop.ink</p>
       </div>
      </div>
     </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container mt-3">
 <% if @user.errors.any? %>
  <div class="errors text-danger">
   <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
   <li>
    <% @user.errors.full_messages.each do |message| %>
     <%= message %>
    <% end %>
   </li>
  </div>
 <% end %>
 <div class="row">
  <div class="col-md-5 mx-auto">
   <h2>User info</h2>
   <%= form_with model:@user, local:true do |f| %>
    <div class="form-group">
     <label for="Book-name">Name</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="profile-image">Image</label>
      <%= f.attachment_field :profile_image %>
    </div>
    <div classs="form-group">
     <label for="Book-Introduct">Introduction</label>
      <%= f.text_area :introduction, class: "form-control" %>
    </div>
    <div class="button mt-2">
     <%= f.submit "Update User", class: "btn btn-secondary" %>
    </div>
   <% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="container mt-3 px-5">
 <div class="row">
  <div class="col-md-3">
   <%= render 'books/list', user: @user %>
    <div class="mt-3">
     <h2>New book</h2>
    </div>
    <%= form_with model: @book, local:true do |f| %>
     <div class="form-group">
      <label for="Book-Title">Title</label>
       <%= f.text_field :title, class: "form-control" %>
     </div>
     <div class="form-group">
      <label for="Book-Opinion">Opinion</label>
       <%= f.text_area :body, class: "form-control" %>
     </div>
     <div class="button">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
     </div>
    <% end %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
    <table class="table">
     <thead>
      <tr>
       <th>image</th>
       <th>name</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
      <% @users.each do |user| %>
      <tr>
       <td>
        <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
       </td>
       <td>
        <%= user.name %>
       </td>
       <td>
        <%= link_to "Show", user_path(user.id) %>
       </td>
      </tr>
      <% end %>
     </tbody>
    </table>
  </div>
 </div>
</div>



<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
　
  
    </div>
    <div class='col-md-8 offset-md-1'>
      
      

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5　px-sm-0">

 <div class="row">
  <div class="col-md-3">
   <%= render "books/list", user: @user %>

   <div class="mt-3">
    <h2>New book</h2>
   </div>
    <%= form_with model: @new_book, local:true do |f| %>
     <div class="form-group">
      <label for="Book-Title">Title</label>
       <%= f.text_field :title, class: "form-control" %>
     </div>
     <div class="form-group">
       <label for="Book-Opinion">Opinion</label>
       <%= f.text_area :body, class: "form-control" %>
     </div>
     <div class="button">
       <%= f.submit "Create Book", class: "btn btn-success" %>
     </div>
    <% end %>
  </div>
  <div class='col-md-8 offset-md-1'>
   <h2>Books</h2>
   <table class="table table-hover">
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
     </tr>
    </thead>
    <tbody>
     <% @books.each do |book| %>
     <tr>
      <td>
       <%= link_to user_path(book.user.id) do %>
        <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
       <% end %>
      </td>
      <td>
       <%= link_to book_path(book.id) do %>
        <%= book.title %>
       <% end %>
      </td>
      <td>
       <%= book.body %>
      </td>
     </tr>
     <% end %>
    </tbody>
   </table>
  </div>


 </div>
</div>


<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
　
  
    </div>
    <div class='col-md-8 offset-md-1'>
      
      

    </div>
  </div>
</div>